import Head from "next/head";
import { Stack, Text, Box } from "@chakra-ui/react";
import Carousel from "../../components/Carousel";

const data = {
  data: {
    name: "Sample Product",
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perferendis excepturi culpa, natus et quae in voluptates illo provident voluptatem voluptate.",
    images: [
      {
        data: {
          product_image_id: 1,
          attributes: {
            image_url:
              "https://images.unsplash.com/photo-1612852098516-55d01c75769a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDR8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=900&q=60",
          },
        },
      },
      {
        data: {
          product_image_id: 2,
          attributes: {
            image_url:
              "https://images.unsplash.com/photo-1627875764093-315831ac12f7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDJ8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=900&q=60",
          },
        },
      },
      {
        data: {
          product_image_id: 3,
          attributes: {
            image_url:
              "https://images.unsplash.com/photo-1571432248690-7fd6980a1ae2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDl8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=900&q=60",
          },
        },
      },
    ],
  },
};

const ProductPage = () => {
  return (
    <>
      <Head>
        <title>Christian Religious Item Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Stack minH={"100vh"} as={"section"}>
          <Box padding={5} bgColor={"white"}>
            <Text fontWeight={"medium"} padding={2} fontSize={"2xl"}>
              {data.data.name}
            </Text>
            <Carousel
              images={data.data.images.map(
                (img) => img.data.attributes.image_url
              )}
            />
            <Text marginTop={10} padding={2}>
              {data.data.description}
            </Text>
          </Box>
        </Stack>
      </main>
    </>
  );
};

export default ProductPage;
