import Head from "next/head";
import NavBar from "../components/NavBar";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar />
      </main>
    </div>
  );
};

export default Home;
